/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e007ebfa4f4b55911b44117
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import React, { Component } from "react";
import { Link } from "react-router-dom";
import Utils from "../utils/utils";

// Redux
import PropTypes from "prop-types";
import { bindActionCreators } from "redux";
import { connect } from "react-redux";

// Material UI
import TextField from "@material-ui/core/TextField";
import Button from "@material-ui/core/Button";
import Select from "@material-ui/core/Select";
import MenuItem from "@material-ui/core/MenuItem";
import InputLabel from "@material-ui/core/InputLabel";
import FormControl from "@material-ui/core/FormControl";
import Chip from "@material-ui/core/Chip";
import Input from "@material-ui/core/Input";

// Custom Actions


// START IMPORT ACTIONS
import OrganizationActions from "../redux/actions/OrganizationActions";
import PartnershipActions from "../redux/actions/PartnershipActions";

// END IMPORT ACTIONS

/** APIs

* actionsOrganization.create
*	@description CRUD ACTION create
*
* actionsPartnership.findBy_organization
*	@description CRUD ACTION findBy_organization
*	@param Objectid key - Id della risorsa _organization da cercare
*
* actionsOrganization.get
*	@description CRUD ACTION get
*	@param ObjectId id - Id resource
*
* actionsPartnership.list
*	@description CRUD ACTION list
*
* actionsOrganization.update
*	@description CRUD ACTION update
*	@param ObjectId id - Id
*

**/

class OrganizationEdit extends Component {
  // Init organization
  constructor(props) {
    super(props);
    this.state = {
      organization: {}
    };
  }

  // Load data on start
  componentDidMount() {
    if (this.props.match.params.id !== "new") {
      this.props.actionsOrganization.loadOrganization(this.props.match.params.id);
      this.props.actionsPartnership.findBy_organization(this.props.match.params.id);
    }
    
    this.props.actionsPartnership.loadPartnershipList();
  }

  // Insert props organization in state
  componentWillReceiveProps(props) {
    this.setState(...this.state, {
      organization: props.organization
    });
  }

  // Save data
  save(event) {
    event.preventDefault();
    if (this.state.organization._id) {
      this.props.actionsOrganization.saveOrganization(this.state.organization).then(data => {
        this.props.history.push("/organizations/");
      });
    } else {
      this.props.actionsOrganization.createOrganization(this.state.organization).then(data => {
        this.props.history.push("/organizations/");
      });
    }
  }

  // Show content
  render() {
    return (
      <div>
        <h1>Organization Edit</h1>
        <form className="myForm" onSubmit={this.save.bind(this)}>

          
          <TextField
            id="Name"
            label="Name"
            value={this.state.organization.Name || ""}
            onChange={Utils.handleChange.bind(this, "organization")}
            margin="normal"
            fullWidth
            required
            {...(!this.state.organization.Name && this.state.organization.Name === ""
              ? { error: true }
              : {})}
          />
          
          
          <TextField
            id="Phone"
            label="Phone"
            value={this.state.organization.Phone || ""}
            onChange={Utils.handleChange.bind(this, "organization")}
            type="number"
            margin="normal"
            fullWidth
          />
          
          {/* RELATIONS */}

          <h2 className="mb-20">Relations</h2>
          
          {/* Relation m:m _partnership with Partnership */}
          
          <FormControl fullWidth className="mb-20">
            <InputLabel htmlFor="_partnership">_partnership</InputLabel>
            <Select
              multiple
              value={this.state.organization._partnership || []}
              onChange={Utils.handleChangeSelect.bind(this, "organization")}
              input={<Input id="_partnership" name="_partnership" />}
              renderValue={selected => (
                <div>
                  {selected.map(value => (
                    <Chip key={value} label={value} />
                  ))}
                </div>
              )}
            >
              {this.props.listPartnership && this.props.listPartnership.map(item => (
                <MenuItem
                  key={item._id}
                  value={item._id}
                  style={{
                    fontWeight:
                      this.state.organization._partnership &&
                      this.state.organization._partnership.indexOf(item._id) === -1
                        ? "regular"
                        : "bold"
                  }}
                >
                  {item._id}
                </MenuItem>
              ))}
            </Select>
          </FormControl>
          
          {/* EXTERNAL RELATIONS */}
          
          {/* External relation with Partnership */}
          
          <h3>Partnership</h3>
          {(!this.props.listPartnership || this.props.listPartnership.length === 0) && 
            <div>No Partnership associated</div>
          }
          {this.props.listPartnership &&
            this.props.listPartnership.map((item, i) => {
              return (
                <Link to={"/partnerships/" + item._id} key={item._id}>
                  {item._id}
                </Link>
              );
            })}

          
          {/* Footer */}
          <div className="footer-card">
            <Link to="/organizations/">Back to list</Link>

            <Button type="submit" variant="contained" color="primary">
              Save
            </Button>
          </div>
        </form>
      </div>
    );
  }
}

// Store actions
const mapDispatchToProps = function(dispatch) {
  return { 
    actionsOrganization: bindActionCreators(OrganizationActions, dispatch),
    actionsPartnership: bindActionCreators(PartnershipActions, dispatch),
  };
};

// Validate types
OrganizationEdit.propTypes = { 
  actionsOrganization: PropTypes.object.isRequired,
  actionsPartnership: PropTypes.object.isRequired,
};

// Get props from state
function mapStateToProps(state, ownProps) {
  return {
    organization: state.OrganizationEditReducer.organization,
    listPartnership: state.OrganizationEditReducer.listPartnership,
    listPartnership: state.OrganizationEditReducer.listPartnership
  };
}

export default connect(
  mapStateToProps,
  mapDispatchToProps
)(OrganizationEdit);
