/* 
* Generated by
* 
*      _____ _          __  __      _     _
*     / ____| |        / _|/ _|    | |   | |
*    | (___ | | ____ _| |_| |_ ___ | | __| | ___ _ __
*     \___ \| |/ / _` |  _|  _/ _ \| |/ _` |/ _ \ '__|
*     ____) |   < (_| | | | || (_) | | (_| |  __/ |
*    |_____/|_|\_\__,_|_| |_| \___/|_|\__,_|\___|_|
*
* The code generator that works in many programming languages
*
*			https://www.skaffolder.com
*
*
* You can generate the code from the command-line
*       https://npmjs.com/package/skaffolder-cli
*
*       npm install -g skaffodler-cli
*
*   *   *   *   *   *   *   *   *   *   *   *   *   *   *   *
*
* To remove this comment please upgrade your plan here: 
*      https://app.skaffolder.com/#!/upgrade
*
* Or get up to 70% discount sharing your unique link:
*       https://app.skaffolder.com/#!/register?friend=5e007ebfa4f4b55911b44117
*
* You will get 10% discount for each one of your friends
* 
*/
// Dependencies
import * as types from "../actionTypes";

// Init
const initialState = {
  partnership: {}
};

// Reducer
export default function PartnershipEditReducer(state = initialState, action) {
  switch (action.type) { 
    
    // Insert here your custom reducers


    // START REDUCERS
    case types.CREATE_PARTNERSHIP_SUCCESS:
      return { ...state, partnership: action.payload };
    case types.FINDBY_PARTNERSHIP_ORGANIZATION_SUCCESS:
      return { ...state, listOrganization: action.payload };
    case types.GET_PARTNERSHIP_SUCCESS:
      return { ...state, partnership: action.payload };
    case types.LIST_ORGANIZATION_SUCCESS:
      return { ...state, listOrganization: action.payload };
    case types.UPDATE_PARTNERSHIP_SUCCESS:
      return { ...state, partnership: action.payload };
     // END REDUCERS
    
    default:
      return state;
  }
}